/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seamfix_qrcode_FaceFeatures */

#ifndef _Included_com_seamfix_qrcode_FaceFeatures
#define _Included_com_seamfix_qrcode_FaceFeatures
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seamfix_qrcode_FaceFeatures
 * Method:    matchpcafeatures
 * Signature: (Ljava/lang/String;)[F
 */
JNIEXPORT jstring JNICALL Java_com_sample_facedetect_MtcnnDetector_cropFace
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif